name: passwordless-auth-dev-sso
services:
  sso:
    container_name: passwordless-auth-dev-keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    restart: always
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./import/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./target/sso.jar:/opt/keycloak/providers/providers.jar
    command: start-dev --import-realm
